### PR TITLE
Add aggressive intake mode to help jams, tweak speeds

### PR DESCRIPTION
**Pull request by a-viv-a**
Tweak speeds, add aggressive intake mode

more changes to come, but these speeds seem better than current <-- this will happen on a calgames branch

feel free to merge with one review, but it would be good to get into the habit of code reviews

### CODE REVIEW

**Review by audreypj — COMMENTED** [review]
Is the command an instant command?

**Comment by a-viv-a** [comment]
> Is the command an instant command?

Which command?

**Review by audreypj — COMMENTED** [review]
the ForceIntakeModeCommand

**Comment by a-viv-a** [comment]
> the ForceIntakeModeCommand

No, it extends commandbase. It uses the force member on the intake to prevent state change as long as the command is live. It's bound to whenheld, so it is live as long as the button is held. This means intake will continue until the button is let go, and then the state machine can progress.

In the future, you can leave comments on particular lines of code so its easier to know the context.

**Comment by audreypj** [comment]
> > the ForceIntakeModeCommand
> 
> No, it extends commandbase. It uses the force member on the intake to prevent state change as long as the command is live. It's bound to whenheld, so it is live as long as the button is held. This means intake will continue until the button is let go, and then the state machine can progress.
> 
> In the future, you can leave comments on particular lines of code so its easier to know the context.

ok cool

**Review by audreypj — APPROVED** [review]
Looks good to me then

**Comment by a-viv-a** [comment]
@LexieLev @BrandonTheBusyBeaver117 it would still be a good idea to look this over and understand how this kind of change is done.

**Pull request merged**
